### GET request to retrieve categories
GET {{baseUrl}}/categories

###

### POST request to create category
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "categoryId": 1,
    "categoryName": "Playing Piano"
}

###