### GET request to retrieve categories
GET {{baseUrl}}/categories

###

### POST request to create category
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "categoryName": "Playing Cricket"
}

###

### DELETE request to remove category by id
DELETE {{baseUrl}}/categories/1

###

### PUT request to update category
PUT {{baseUrl}}/categories/1
Content-Type: application/json

{
  "categoryId": 1,
  "categoryName": "Playing yo yo"
}
