### GET request to example server
GET {{baseUrl}}/hello
###

### POST request to example server
POST {{baseUrl}}/hello
Content-Type: application/json
Accept: application/json

"Jay"
###

### GET request to example server
GET {{baseUrl}}/hello/test123
###